<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <UserSecretsId>dotnet-IntegrityService-393DD967-2EB1-49CF-AC41-ECF289DC3BB8</UserSecretsId>
        <StartupObject>IntegrityService.Program</StartupObject>
        <ApplicationIcon>..\Assets\fim.ico</ApplicationIcon>
        <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
        <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <PublishTrimmed>True</PublishTrimmed>
        <EnableTrimAnalyzer>True</EnableTrimAnalyzer>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
        <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="fim-log.db" />
        <None Remove="fim.db" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FastCache.Cached" Version="1.8.2" />
        <PackageReference Include="JetBrains.Annotations" Version="2024.3.0" />
        <PackageReference Include="LiteDB" Version="5.0.21" />
        <PackageReference Include="Microsoft.Diagnostics.Tracing.TraceEvent" Version="3.1.19" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.0" />
        <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="9.0.1" />
        <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
        <PackageReference Include="NUlid" Version="1.7.2" />
        <PackageReference Include="Serilog" Version="4.2.0" />
        <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.EventLog" Version="4.0.0" />
        <PackageReference Include="System.Diagnostics.Tracing" Version="4.3.0" />
        <PackageReference Include="System.IO.FileSystem.AccessControl" Version="5.0.0" />
        <PackageReference Include="TBC.Common.Configuration.Registry" Version="2.1.0" />
        <PackageReference Include="Utf8Json" Version="1.3.7" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\NtfsReader\NtfsReader.csproj" />
    </ItemGroup>
</Project>
