<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <IsTestProject>true</IsTestProject>
    <PublishAot>false</PublishAot>
    <PublishTrimmed>false</PublishTrimmed>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.6.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.6.4" /> 
  </ItemGroup>
  <ItemGroup><ProjectReference Include="..\WinFIMLog\WinFIMLog.csproj" /></ItemGroup>
</Project>
